name: PRInfection

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          tools: composer:v2
          extension-csv: xdebug
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run Infection for added files only
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection -j2 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered
