name: PRInfection

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          tools: composer:v2
          extension-csv: xdebug
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run Infection threshold 80%
        run: |
          vendor/bin/infection --min-msi=80 --ignore-msi-with-no-mutations
